In [0]:
import pandas as pd
import json

In [0]:
raw_data = """
        {
          "city": ["Recife", "Rio de Janeiro", "Maceio", "Gravatá","São Paulo", "Curitiba"],
          "rank": ["1st", "2st", "1st", "2st", "1st","2st"],
          "name": ["Daniel", "Fernanda", "Junior", "Elisa", "João", "Pedro"],
          "score": ["44", "52", "51", "47", "48", "62"]
        }
          """
print(type(raw_data)) #str

In [0]:
data = json.loads(raw_data) #convertendo str para python object utilizando json
print(data)
print(type(data)) #class (dict)

In [0]:
data['name'][0]

In [0]:
df = pd.DataFrame(data) #usando o DataFrame para transformar a str em uma tabela
df

df.to_csv('')